### ISSUE TITLE
Prerequisites / Logistics - Add list of NoVNC supported browsers

### ISSUE THREAD

**Issue by mflannery** [johnsimcall/redhatgov.github.io#3]
From: https://github.com/novnc/noVNC#browser-requirements

Browser Requirements

noVNC uses many modern web technologies so a formal requirement list is not available. However these are the minimum versions we are currently aware of:

    Chrome 49, Firefox 44, Safari 10, Opera 36, IE 11, Edge 12

**Comment by rickmanley-nc** [comment]
Added to the prereq page
